### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bakera81** [datacamp/courses-intro-to-r#11]
A user noted that it should say "row names" instead of "column names"
![image](https://cloud.githubusercontent.com/assets/8726176/17904942/51e75d38-693f-11e6-850c-56f71395aabc.png)

**Comment by filipsch** [comment]
Thanks, I'll update!

**Comment by filipsch** [comment]
@bakera81 Next time you raise an issue, could you be specific about the exercise it occurred? That way we don't have to look for it through the database. Thanks!

**Comment by bakera81** [comment]
Of course, sorry about that!
