### ISSUE TITLE
error when knit

### ISSUE THREAD

**Issue by ozonesk** [datacamp/courses-intro-to-r#22]
I download the zip of this project and open the chapter1.Rmd on Rstudio then knit to html and it had the error like this

![screen shot 2017-02-05 at 20 33 06](https://cloud.githubusercontent.com/assets/19890765/22626551/66083a78-ebe2-11e6-9e39-9f63d3c05e99.png)

what should I do for run it?

**Comment by filipsch** [comment]
Hi @ozonesk, we use something that looks like an R Markdown file for coding up exercises on DataCamp, but you cannot use the `knitr` package to net the documents into an html or pdf. The only way to take our content in the way that it's supposed to be taken, is through DataCamp.com..
