### ISSUE TITLE
'Sex' instead of 'Gender' in exercises

### ISSUE THREAD

**Issue by hugobowne** [datacamp/courses-intro-to-r#31]
In [this exercise ](https://campus.datacamp.com/courses/free-introduction-to-r/chapter-4-factors-4?ex=1 )and several that follow, 'Sex' is incorrectly referred to as 'Gender'. 

@ludov04 note4d a student providing such feedback (I have encountered the same in other courses):

![screenshot 2017-06-08 12 43 18](https://user-images.githubusercontent.com/4182382/26940283-134e1f20-4c48-11e7-9198-7657d31cad8e.png)

[According to wikipedia](https://en.wikipedia.org/wiki/Sex_and_gender_distinction) (many other references but this was easiest) ,

> The World Health Organization (WHO) similarly states that "'sex' refers to the biological and physiological characteristics that define men and women" and that "'male' and 'female' are sex categories".

This is both a socially and politically charged issue. I would have edited the exercise noted and issued a PR but as it seems to propagate throughout the course I am raising this issue. Happy to discuss further!

**Comment by yashasroy** [comment]
Fixed in https://github.com/datacamp/courses-intro-to-r/pull/40.
