### ISSUE TITLE
Minor typo in exercise description

### ISSUE THREAD

**Issue by sabrinamoin** [datacamp/courses-intro-to-r#33]
### Summary

Regarding exercise: https://campus.datacamp.com/courses/free-introduction-to-r/chapter-4-factors-4?ex=4:

<img width="951" alt="factors" src="https://user-images.githubusercontent.com/10160857/30516933-7da16734-9b1b-11e7-8c4a-44b6b0f71822.PNG">

Repetition of the word "order".

**Comment by yashasroy** [comment]
Fixed in https://github.com/datacamp/courses-intro-to-r/pull/35
