### ISSUE TITLE
Student feedback

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-intro-to-r#37]
Hello I am completely the intro to R course which I am finding very valuable. I think it is a really well thought-at training program and I am enjoying it a lot. However, I just got to the module on factors and was really disappointed that DataCamp is using gender as the example of a categorical variable. There are so many options to pick from here and DataCamp has chosen one which is a sensitive issue for many people and I am sure many of DataCamp's users. Is it possible for this to be changed? It seems like such a silly thing to have in an otherwise awesome training program. Kind regards Emma

Cf emma.bones@nousgroup.com.au, #51193

**Comment by ncarchedi** [comment]
Fixed with https://github.com/datacamp/courses-intro-to-r/pull/36. I'll review the PR this week and try to get it merged.

**Comment by yashasroy** [comment]
Likewise.

**Comment by yashasroy** [comment]
Fixed in https://github.com/datacamp/courses-intro-to-r/pull/40.
