### ISSUE TITLE
Typo in Exercise

### ISSUE THREAD

**Issue by ramnathv** [datacamp/courses-intro-to-r#42]
In this [exercise](https://campus.datacamp.com/courses/free-introduction-to-r/chapter-5-data-frames?ex=6), the first bullet point should read 

> selects the value at the first row and __second column__ in `mydf`

![image](https://user-images.githubusercontent.com/346288/34644880-4f59a19e-f2f4-11e7-8da0-38df0b65944a.png)

**Comment by yashasroy** [comment]
Thanks! Fixed in https://github.com/datacamp/courses-intro-to-r/pull/43.
