### ISSUE TITLE
Chapter 1 in Turkish language

### ISSUE THREAD

**Issue by sylarbui** [datacamp/courses-intro-to-r#53]
Issue: Chapter 1 is now showing in the Turkish language.
Link: https://campus.datacamp.com/courses/free-introduction-to-r/chapter-1-ra-ilk-adim?ex=1

<img width="1440" alt="screen shot 2018-10-29 at 13 32 27" src="https://user-images.githubusercontent.com/40219472/47633037-18e83200-db7f-11e8-8cd4-06baf421b6ea.png">

For Support Team:
Zendesk ticket: https://datacamp.zendesk.com/agent/tickets/121202

cc @Robert-cabral  @MelRemy  @kasthynguyen 
<div style="background-color:#BBDEFB;padding:10px;border-radius:5px;" id="zdArea">                             	                                                              <div style="text-decoration:underline;margin-bottom:5px;color:#00000082;" id="zd-ReservedAreaHeader">                 <span class="zdDescription" style="font-weight: bold;"><h3 style="margin:0px;padding:0px;">Zendesk Information</h3></span>                 <div class="zdValue"></div>             </div>                          <div class="ValueTypeField" style id="zd-TicketLinkUpdateIssue"><span style="margin-right:5px;">&#9679;</span>                 <span class="zdDescription" style="font-weight: bold;">Linked with zendesk ticket:</span>                 <span class="zdValue"><a href="https://datacamp.zendesk.com/agent/tickets/121319" target="_blank">121319</a></span>             </div>                          <div class="ValueTypeField" style id="zd-SupportCount"><span style="margin-right:5px;">&#9679;</span>                 <span class="zdDescription" style="font-weight: bold;">Total Number of additional reports:</span>                 <span class="zdValue">10</span>             </div>             </div>

**Comment by Robert-cabral** [comment]
@sylarbui I'm looking at the course, and everything appears to be in English: https://campus.datacamp.com/courses/free-introduction-to-r/chapter-4-factors-4?ex=5. 

Also, the URL you provided generates an error for me.

![image](https://user-images.githubusercontent.com/36449860/47654982-65714480-db62-11e8-9338-2f8c92f7a96f.png)

My guess:
1. Either this was already fixed
2. Perhaps the URL you have is for an open course that was deleted?

**Comment by yashasroy** [comment]
> My guess:
> 
> 1. Either this was already fixed

@Robert-cabral Correct - this has been fixed by the Teach engineering team. Thanks for flagging, @sylarbui.
